<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetJobTable
     */

    static public $types = array(
      'full-time' => 'Full time',
      'part-time' => 'Part time',
      'freelance' => 'Freelance',
    );
 
    public function getTypes()
    {
      return self::$types;
    }

    public static function getInstance()

    {
        return Doctrine_Core::getTable('JobeetJob');
    }
}
?>
